# Generated by Django 4.1 on 2026-03-23 03:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('cv_id', models.AutoField(primary_key=True, serialize=False)),
                ('cv_name', models.CharField(max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'core_values',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=150)),
                ('region', models.CharField(default='Region V', max_length=50)),
                ('division', models.CharField(default='Division of Sorsogon', max_length=100)),
                ('district', models.CharField(default='Bulan North District', max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'schools',
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('sy_id', models.AutoField(primary_key=True, serialize=False)),
                ('sy_label', models.CharField(max_length=20, unique=True)),
                ('sy_start', models.DateField(blank=True, null=True)),
                ('sy_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'school_years',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('adviser', 'Adviser'), ('principal', 'Principal'), ('both', 'Both')], default='adviser', max_length=20)),
                ('school', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='reportcard.school')),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('lrn', models.CharField(max_length=12, unique=True)),
                ('last_name', models.CharField(max_length=80)),
                ('first_name', models.CharField(max_length=80)),
                ('middle_initial', models.CharField(blank=True, max_length=2, null=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('school', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='reportcard.school')),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('section_name', models.CharField(max_length=50)),
                ('adviser', models.ForeignKey(blank=True, db_column='adviser_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reportcard.teacher')),
                ('school', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='reportcard.school')),
                ('school_year', models.ForeignKey(db_column='sy_id', on_delete=django.db.models.deletion.CASCADE, to='reportcard.schoolyear')),
            ],
            options={
                'db_table': 'sections',
            },
        ),
        migrations.CreateModel(
            name='LearningArea',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_code', models.CharField(max_length=20, unique=True)),
                ('area_name', models.CharField(max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('parent_area', models.ForeignKey(blank=True, db_column='parent_area_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reportcard.learningarea')),
            ],
            options={
                'db_table': 'learning_areas',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_year', models.ForeignKey(db_column='sy_id', on_delete=django.db.models.deletion.CASCADE, to='reportcard.schoolyear')),
                ('section', models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.CASCADE, to='reportcard.section')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='reportcard.student')),
            ],
            options={
                'db_table': 'enrollments',
                'unique_together': {('student', 'school_year')},
            },
        ),
        migrations.CreateModel(
            name='BehaviorStatement',
            fields=[
                ('bs_id', models.AutoField(primary_key=True, serialize=False)),
                ('statement_text', models.CharField(max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('core_value', models.ForeignKey(db_column='cv_id', on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='reportcard.corevalue')),
            ],
            options={
                'db_table': 'behavior_statements',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('att_id', models.AutoField(primary_key=True, serialize=False)),
                ('jun_school', models.PositiveSmallIntegerField(default=0)),
                ('jun_present', models.PositiveSmallIntegerField(default=0)),
                ('jul_school', models.PositiveSmallIntegerField(default=0)),
                ('jul_present', models.PositiveSmallIntegerField(default=0)),
                ('aug_school', models.PositiveSmallIntegerField(default=0)),
                ('aug_present', models.PositiveSmallIntegerField(default=0)),
                ('sep_school', models.PositiveSmallIntegerField(default=0)),
                ('sep_present', models.PositiveSmallIntegerField(default=0)),
                ('oct_school', models.PositiveSmallIntegerField(default=0)),
                ('oct_present', models.PositiveSmallIntegerField(default=0)),
                ('nov_school', models.PositiveSmallIntegerField(default=0)),
                ('nov_present', models.PositiveSmallIntegerField(default=0)),
                ('dec_school', models.PositiveSmallIntegerField(default=0)),
                ('dec_present', models.PositiveSmallIntegerField(default=0)),
                ('jan_school', models.PositiveSmallIntegerField(default=0)),
                ('jan_present', models.PositiveSmallIntegerField(default=0)),
                ('feb_school', models.PositiveSmallIntegerField(default=0)),
                ('feb_present', models.PositiveSmallIntegerField(default=0)),
                ('mar_school', models.PositiveSmallIntegerField(default=0)),
                ('mar_present', models.PositiveSmallIntegerField(default=0)),
                ('apr_school', models.PositiveSmallIntegerField(default=0)),
                ('apr_present', models.PositiveSmallIntegerField(default=0)),
                ('enrollment', models.OneToOneField(db_column='enrollment_id', on_delete=django.db.models.deletion.CASCADE, to='reportcard.enrollment')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='ObservedValue',
            fields=[
                ('ov_id', models.AutoField(primary_key=True, serialize=False)),
                ('q1', models.CharField(blank=True, choices=[('AO', 'Always Observed'), ('SO', 'Sometimes Observed'), ('RO', 'Rarely Observed'), ('NO', 'Not Observed')], max_length=2, null=True)),
                ('q2', models.CharField(blank=True, choices=[('AO', 'Always Observed'), ('SO', 'Sometimes Observed'), ('RO', 'Rarely Observed'), ('NO', 'Not Observed')], max_length=2, null=True)),
                ('q3', models.CharField(blank=True, choices=[('AO', 'Always Observed'), ('SO', 'Sometimes Observed'), ('RO', 'Rarely Observed'), ('NO', 'Not Observed')], max_length=2, null=True)),
                ('q4', models.CharField(blank=True, choices=[('AO', 'Always Observed'), ('SO', 'Sometimes Observed'), ('RO', 'Rarely Observed'), ('NO', 'Not Observed')], max_length=2, null=True)),
                ('enrollment', models.ForeignKey(db_column='enrollment_id', on_delete=django.db.models.deletion.CASCADE, to='reportcard.enrollment')),
                ('statement', models.ForeignKey(db_column='bs_id', on_delete=django.db.models.deletion.CASCADE, to='reportcard.behaviorstatement')),
            ],
            options={
                'db_table': 'observed_values',
                'unique_together': {('enrollment', 'statement')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('q1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('q2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('q3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('q4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('area', models.ForeignKey(db_column='area_id', on_delete=django.db.models.deletion.CASCADE, to='reportcard.learningarea')),
                ('enrollment', models.ForeignKey(db_column='enrollment_id', on_delete=django.db.models.deletion.CASCADE, to='reportcard.enrollment')),
            ],
            options={
                'db_table': 'grades',
                'unique_together': {('enrollment', 'area')},
            },
        ),
    ]
